name: Deploy User App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-user:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Install dependencies and build
      - name: Install & Build
        run: |
          npm install
          npm run build

      # 4️⃣ Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # 5️⃣ Upload to S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./dist/ s3://userpannel22 --delete

      # 6️⃣ CloudFront invalidation
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
