name: Deploy User Panel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies & Build
        run: |
          cd user
          npm ci
          npm run build
          # Detect build output folder
          if [ -d dist ]; then
            echo "BUILD_DIR=dist" >> $GITHUB_ENV
          elif [ -d build ]; then
            echo "BUILD_DIR=build" >> $GITHUB_ENV
          else
            echo "No build folder found!"
            exit 1
          fi

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: sms-frontend-apps
          AWS_REGION: ap-south-1
          SOURCE_DIR: user/${{ env.BUILD_DIR }}
          DEST_DIR: user
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        with:
          distribution-id: ${{ secrets.CLOUDFRONT_DIST_ID }}
          paths: "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
