name: Deploy User App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-user:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout private repo
      - name: Checkout User Repo
        uses: actions/checkout@v3
        with:
          repository: Sharmila127/smsreactuserpannel-sharmila
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 1

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install and Build
      - name: Install & Build
        run: |
          npm install
          npm run build

      # 4. Sync User App to S3
      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: sms-frontend-app
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
          SOURCE_DIR: build
          DEST_DIR: user

      # 5. Invalidate CloudFront
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v1
        with:
          distribution-id: E2FC1QDHTE5RCX
          paths: "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
